// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0pu3uGkbW50KHV17kNOmp-CAkIwpI4oQ',
    appId: '1:962815003922:android:315bb97e95fea2d74877cb',
    messagingSenderId: '962815003922',
    projectId: 'cima-app2023',
    storageBucket: 'cima-app2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEgB_6_WEDle1LMouBMtEih4IvNFf0w4Y',
    appId: '1:962815003922:ios:7110e9bdf62ea6264877cb',
    messagingSenderId: '962815003922',
    projectId: 'cima-app2023',
    storageBucket: 'cima-app2023.appspot.com',
    iosClientId: '962815003922-j5ti2v2dqigvqu8mhmf3au8miu9215or.apps.googleusercontent.com',
    iosBundleId: 'com.uabc.cimarronPsic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEgB_6_WEDle1LMouBMtEih4IvNFf0w4Y',
    appId: '1:962815003922:ios:7110e9bdf62ea6264877cb',
    messagingSenderId: '962815003922',
    projectId: 'cima-app2023',
    storageBucket: 'cima-app2023.appspot.com',
    iosClientId: '962815003922-j5ti2v2dqigvqu8mhmf3au8miu9215or.apps.googleusercontent.com',
    iosBundleId: 'com.uabc.cimarronPsic',
  );
}
